### ISSUE TITLE
Natuknice

### ISSUE THREAD

**Issue by KarlaSalamun** [petarsusac/zavrsni#1]
https://github.com/petarsusac/zavrsni/blob/d4d23a4820ea7ed274b9c3c62c722be1a787e553/uvod.tex#L4

- kad nabrajaš stvari u natuknicama, na kraju svake natuknice mora biti zarez, a na kraju zadnje mora biti točka
- na početku natuknice je malo početno slovo

**Comment by petarsusac** [comment]
Popravljeno 98487c4
